### ISSUE TITLE
Failing initial Migrations

### ISSUE THREAD

**Issue by higstar** [mpkasp/django-bom#2]
Applying bom.0001_squashed_0018_auto_20170418_0330...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 93, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "bom_distributorpart" does not exist

**Comment by higstar** [comment]
I have progressed by just deleting the migrations in:
/usr/local/lib/python2.7/site-packages/bom/migrations

**Comment by mpkasp** [comment]
@higstar I'm not able to reproduce this issue, can you share your set up? Here's what I ran in a new virtual environment running python 2.7.10 and django 1.11:

```
django-admin startproject mysite
cd mysite/
python manage.py migrate
pip install django-bom```

Update settings.py to add `'bom',` to `INSTALLED_APPS`

Finally, 
```python manage.py migrate```

With an output:
```
Operations to perform:
  Apply all migrations: admin, auth, bom, contenttypes, sessions
Running migrations:
  Applying bom.0001_squashed_0018_auto_20170418_0330... OK
  Applying bom.0002_auto_20170616_0420... OK```

**Comment by higstar** [comment]
Thanks for the points, I had not setup the project as you have here...this helped a lot.
FYI, I'm still working through it (not able to spend much time each day, but I do appreciate your help).
Adding default templates "bom.context_processors.bom_config" has helped, however I'm not yet up to that.
Consider this issue closed (user error).

**Comment by mpkasp** [comment]
Sounds good. Happy to help get you up and running, it's a learning experience for me too to make the tool easier to use :) @higstar
