### ISSUE TITLE
Initial migration fails on "table bom_distributorpart does not exist"

### ISSUE THREAD

**Issue by proffalken** [mpkasp/django-bom#4]
Hello! I'm new to the project but hoping to use it for my business.

I've hit an issue with the initial install after following the instructions in #3 , I get the following error:

```
(indabom) [mmw@rincewind indabom]$ ./manage.py migrate
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: admin, auth, bom, contenttypes, sessions
Running migrations:
  Applying bom.0001_squashed_0018_auto_20170418_0330...Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 109, in __exit__
    self.execute(sql)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/mmw/.virtualenvs/indabom/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'indabom.bom_distributorpart' doesn't exist")
```

It's been a while since I last touched Django (I tend to use flask these days), but it looks to me as if there's a migration missing that creates that table?

This is from the latest version available in pip:

```
Django==1.11.14
django-bom==0.67
mysqlclient==1.3.13
pytz==2018.5
```

**Comment by mpkasp** [comment]
Hi @proffalken sorry about the delay - I just got back from holiday. I tried to reproduce this issue and was unsuccessful. I just updated the readme to show the steps I took starting from scratch with a new django project. Maybe that will help us try to find what's going on. Let me know if this resolves this issue for you.

**Comment by mpkasp** [comment]
@proffalken let me know if you can give me better steps to reproduce, otherwise closing this issue as it's been a few months

**Comment by proffalken** [comment]
@mpkasp apologies for not coming back to this, I'm using a more simple solution (libre-office spreadsheet!) for now, if that changes I'll come back to this.

Thanks.

**Comment by mpkasp** [comment]
@proffalken no problem! I'd love to hear what's missing from indabom if you can spare a minute, shoot me an email at info@indabom.com
